### ISSUE TITLE
添加房间号就出现报错

### ISSUE THREAD

**Issue by solo7917** [yunhuanyx/biliLiveNotification#2]
![Quicker_20231123_202219](https://github.com/yunhuanyx/biliLiveNotification/assets/139970150/c3f373ff-57f9-4138-8396-341b6097457f)

**Comment by solo7917** [comment]
![Quicker_20231123_202219](https://github.com/yunhuanyx/biliLiveNotification/assets/139970150/bb02c5eb-dd9c-4744-be3e-e984097706cf)

**Comment by yunhuanyx** [comment]
你试一下我发的这个看看有没有问题
[Uploading bilibili_Live_Notification.zip…]()

**Comment by yunhuanyx** [comment]
你试一下我发的这个版本有没有问题
https://gofile.io/d/90sGtM

**Comment by solo7917** [comment]
> 你尝试一下我发布的这个版本没有问题 https://gofile.io/d/90sGtM

谢谢，能正常使用了！

**Comment by yunhuanyx** [comment]
> > 你尝试一下我发布的这个版本没有问题https://gofile.io/d/90sGtM
> 
> 谢谢，能正常使用了！

发布界面的多修了一个bug，可以换成发布界面那个，昨天晚上改的时候没发现那个bug

**Comment by solo7917** [comment]
> > > 你尝试一下我发布的这个版本没有问题https://gofile.io/d/90sGtM
> > 
> > 
> > 谢谢，能正常使用了！
> 
> 发布界面的多修了一个bug，可以换成发布界面那个，昨天晚上改的时候没发现那个bug

好的谢谢！
